* There is a *BIG* difference between xwiki-core-macro-blahblah & xwiki-core-rendering-macro-blahblah. The former versions (some of them) depend on the early xwiki-core-rendering module. As a result xwiki-core-rendering.jar ends up in WEB-INF/lib directory of the final XE distribution. Unfortunately some components (like office importer) pick up this library (at runtime) instead of the new ones, thus leading to a terrible NoSuchMethodError exception (because the api has changed).
git-svn-id: https://svn.xwiki.org/svnroot/xwiki/platform/core/trunk@15351 f329d543-caf0-0310-9063-dda96c69346f